export default Data = [
  {
   id:'bid',
   name:'bid',
   titre:'Marchandise',
   images:'/Users/mfoulouyvesmarcel/Desktop/Testons/AwesomeProject/src/images/Asong.jpg',
   description:'Ici je fais la description des produits qui pourront etre dans notre projet',
   image: "https://picsum.photos/800/500",
  },
  {
   id:'Mfoulou',
   name:'Mfoulou',
   titre:'Marchandise',
   images:'/Users/mfoulouyvesmarcel/Desktop/Testons/AwesomeProject/src/images/Asong.jpg',
   description:'Ici je fais la description des produits qui pourront etre dans notre projet',
   image: "https://picsum.photos/800/500",
 },
 {
  id:'Jpoint',
  name:'Jpoint',
  titre:'Marchandise',
  images:'/Users/mfoulouyvesmarcel/Desktop/Testons/AwesomeProject/src/images/Asong.jpg',
  description:'Ici je fais la description des produits qui pourront etre dans notre projet',
  image: "https://picsum.photos/800/500",
  },
  {
   id:'Fidel',
   name:'Fidel',
   titre:'Marchandise',
   images:'/Users/mfoulouyvesmarcel/Desktop/Testons/AwesomeProject/src/images/Asong.jpg',
   description:'Ici je fais la description des produits qui pourront etre dans notre projet',
   image: "https://picsum.photos/800/500",
   },
   {
    id:'Roland',
    name:'Roland',
    titre:'Marchandise',
    images:'/Users/mfoulouyvesmarcel/Desktop/Testons/AwesomeProject/src/images/Asong.jpg',
    description:'Ici je fais la description des produits qui pourront etre dans notre projet',
    image: "https://picsum.photos/800/500",
    },
]
